### ISSUE TITLE
Site can't be reached

### ISSUE THREAD

**Issue by emmacarli** [pmelchior/aas2rss#3]
Hello! 
I can't reach  http://aas2rss.pmelchior.net/ (or HTTPS) and neither can my RSS feed. 
Thanks in advance for your help! 
Emma

**Comment by pmelchior** [comment]
Yes, I know. The AAS has removed public access to those job posting, so they cannot be collected by other servers anymore. I therefore had to shut down the service. You will have to go through their website now.

Where did you find information about AAS2RSS?

**Comment by emmacarli** [comment]
OK, no problem, thank you. I looked up "AAS job register RSS feed" on Google and ended up on this  [page](https://www.ita.uni-heidelberg.de/~pmelchior/display.php?subject=aas2rss).

**Comment by pmelchior** [comment]
This website is so outdated! And I don't have access to that server anymore, so it'll probably stay up forever.
